server:
  port: 10880
dubbo:
  application:
    name: tanhua-server
  registry:
    address: zookeeper://192.168.211.160:2181
  consumer:
    check: false
# log
logging:
  level:
    root: info
    com:
      tanhua: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %msg - %logger{15}%n\'

tanhua:
  sms:
    validateCodeTemplateCode: SMS_189646456735416640
    signName: test
    parameterName: code
    accessKeyId: LTAI4FyG7DDp4FbxbgbcxrabsdfhmgfidgeAt
    accessKeySecret: LBXIjhregWlxvVmtsrdtR2bphjsp9CVzYzqojUfJ6ezi
  oss:
    endpoint: http://oss-cn-shenzhen.aliyuncs.com
    bucketName: test
    url: https://sztanhua.oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAIya4FyG7DdsdsyafDp4FhdafmgfidgeAt
    accessKeySecret: LBXIjWlVmyerhdR2basdfpp9CasdfvVzYzqojUfJ6ezi
  face:
    appId: 22356943456797516
    apiKey: uD745kEBD87567htO023453soeMB6kuMZ3456TZi
    secretKey: sMGUX8dftgtzP745hc0rtyeBf546vy3rbGYuX456iK6MZCEF
  huanxin:
    url: http://a1.easemob.com/
    orgName: 11121909068961181842
    appName: test
    clientId: YXA6fVCzrQjySx-6Ffsq2PA
    clientSecret: jHByJ5uc4HQQ
  # redis key prefix for validate code
  redisValidateCodeKeyPrefix: VALIDATECODE_
  # 密钥
  secret: 098f6bcd4621d373cade4e832627b4f6

spring:
  redis:
    host: 192.168.211.160
    port: 6379
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB

# 分布式文件系统配置
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  thumb-image:
    width: 150
    height: 150
  tracker-list: 192.168.211.160:22122
  web-server-url: http://192.168.211.160:8888/

rocketmq:
  name-server: 192.168.211.160:9876
  producer:
    group: tanhua

